# gradle.properties
# L2kt Build Configuration

# Kotlin
kotlin.code.style=official

# JVM args para build (mais RAM para compilar 1.660 arquivos)
org.gradle.jvmargs=-Xmx2g -XX:+UseG1GC -XX:MaxMetaspaceSize=512m

# Parallel build
org.gradle.parallel=true
org.gradle.caching=true
kotlin.jvm.target.validation.mode=warning
